# Authors of code:
# - Carl-Johan Erikson


# Template for secrets. Kinda like ConfigMap but very hush hush
# Replace <REPLACE-ME> with base64 encoded value
# On Linux: echo -n <string> | base64
# Then rename the file secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: system-secrets
type: Opaque  # Arbitrary key/value pairs
data:
  mongodb-url: <REPLACE-ME>